### ISSUE TITLE
value.replace is not a function error on ui-number-mask

### ISSUE THREAD

**Issue by luisfontes** [assisrafael/angular-input-masks#75]
Hi, thanks for building this up.

I'm getting an `value.replace is not a function` error when trying to use the ui-number-mask directive. I'm using the other directives such as cep, cpf and these are working as intended.

This is my markup (jade):
```html
md-input-container(flex="30")
  label Número
  input(type="number" 
        name="numero" 
        required
        ng-model="vm.user.address.numero"
        ui-number-mask)
  div(ng-messages="checkoutForm.numero.$error" ng-if="checkoutForm.numero.$touched")
    div(ng-message="required") Informe um número
    div(ng-message="number") Somente números
```

And this is what logs on chrome developer tools:
```javascript
TypeError: [gfb-app Error]value.replace is not a function
    at Object.clearDelimitersAndLeadingZeros (http://localhost:3000/scripts/main.js:16622:27)
    at Array.parser (http://localhost:3000/scripts/main.js:16214:41)
    at NgModelController.$$parseAndValidate (http://localhost:3000/scripts/vendor.js:28076:39)
    at NgModelController.$commitViewValue (http://localhost:3000/scripts/vendor.js:28066:11)
    at http://localhost:3000/scripts/vendor.js:28199:15
    at Scope.$get.Scope.$eval (http://localhost:3000/scripts/vendor.js:19273:29)
    at Scope.$get.Scope.$apply (http://localhost:3000/scripts/vendor.js:19372:24)
    at NgModelController.$$debounceViewValueCommit (http://localhost:3000/scripts/vendor.js:28198:15)
    at NgModelController.$setViewValue (http://localhost:3000/scripts/vendor.js:28170:13)
    at HTMLInputElement.listener (http://localhost:3000/scripts/vendor.js:24591:13) undefined(anonymous function) @ angular.js:11655$get @ angular.js:8596(anonymous function) @ exception-handler.provider.coffee:27$get.Scope.$apply @ angular.js:14567NgModelController.$$debounceViewValueCommit @ angular.js:23391NgModelController.$setViewValue @ angular.js:23363listener @ angular.js:19784n.event.dispatch @ jquery-2.1.3.min.js:3n.event.add.r.handle @ jquery-2.1.3.min.js:3
angular.js:11655 error: [gfb-app Error]value.replace is not a function Object {exception: TypeError: [gfb-app Error]value.replace is not a function, cause: undefined}(anonymous function) @ angular.js:11655Logger.error @ logger.coffee:15(anonymous function) @ exception-handler.provider.coffee:37$get.Scope.$apply @ angular.js:14567NgModelController.$$debounceViewValueCommit @ angular.js:23391NgModelController.$setViewValue @ angular.js:23363listener @ angular.js:19784n.event.dispatch @ jquery-2.1.3.min.js:3n.event.add.r.handle @ jquery-2.1.3.min.js:3
```

I'm using angular 1.3.15 with ngMaterial.

**Comment by assisrafael** [comment]
Can you provide a live demo to reproduce your problem (like http://plnkr.co/)?

**Comment by luisfontes** [comment]
I found the problem. I was defining the input type as "number", when I removed the type declaration it worked.

Thanks.
